### ISSUE TITLE
Remove entry in request-table when runtime monitoring has finished

### ISSUE THREAD

**Issue by sandersig** [oslofjord-twin/OslofjordFE#2]
The solution now, never deletes any entries in the request-table after the done-variable in the table has been set to "true". This makes the table only larger for every user that wants to check if a position in the fjord is suitable for a specie. 

I have run some performance tests on the API, and because this table only becomes larger, it really slows down the performance in the twin. The front-end queries the whole table, and not just the entry with the correct request-id when waiting for the runtime to finish, making the request requiring more and more time for every entry that is inserted. 

Solution: 
I think we should delete every entry in the request-table after the run-time monitoring has finished the request and set the field "done" to "true". In this way we can keep up the performance of the twin.

**Comment by ingvildemilie** [comment]
I have now added a new mutation that removes the latest request entry in the request table after it has finished processing.
